language: java
addons:
  sonarcloud:
    organization: "leonardxfce-github"
    token:
      secure: $SONAR_TOKEN
script:
  - mvn clean test jacoco:report coveralls:report
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.m2/repository
    - $HOME/.sonar/cache