language: java
sudo: false
os: linux
install: true
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: "leonardxfce-github"
    token:
      secure: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
after_success:
  - mvn clean test jacoco:report coveralls:report