language: java
sudo: false
os: linux
install: true
jdk: oraclejdk8
script:
  - mvn clean test jacoco:report coveralls:report
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.m2/repository
    - $HOME/.sonar/cache